// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement("main", {
                  className: "lg:max-w-4xl mx-auto grid grid-cols-5"
                }, React.createElement("nav", {
                      className: "col-span-1 sticky self-start top-2 "
                    }, React.createElement("a", {
                          className: "block",
                          href: "#h0"
                        }, "Header 0"), React.createElement("a", {
                          className: "block pl-6",
                          href: "#sh0"
                        }, "Subheader 0"), React.createElement("a", {
                          className: "block",
                          href: "#h1"
                        }, "Header 1"), React.createElement("a", {
                          className: "block",
                          href: "#h2"
                        }, "Header 2"), React.createElement("a", {
                          className: "block pl-6",
                          href: "#sh2"
                        }, "Subheader 2"), React.createElement("a", {
                          className: "block",
                          href: "#h3"
                        }, "Header 3")), React.createElement("div", {
                      className: "col-span-4"
                    }, React.createElement("h2", {
                          id: "h0"
                        }, "Header 0"), React.createElement("p", {
                          className: "mb-72"
                        }, "filler"), React.createElement("h3", {
                          id: "sh0"
                        }, "Subheader 0"), React.createElement("p", {
                          className: "mb-72"
                        }, "filler"), React.createElement("h2", {
                          id: "h1"
                        }, "Header 1"), React.createElement("p", {
                          className: "mb-72"
                        }, "filler"), React.createElement("h2", {
                          id: "h2"
                        }, "Header 2"), React.createElement("p", {
                          className: "mb-72"
                        }, "filler"), React.createElement("h3", {
                          id: "sh2"
                        }, "Subheader 2"), React.createElement("p", {
                          className: "mb-72"
                        }, "filler"), React.createElement("h2", {
                          id: "h3"
                        }, "Header 3"), React.createElement("p", {
                          className: "mb-72"
                        }, "filler"))));
}

export {
  s ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
