// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function ManualCoreExamples(Props) {
  return React.createElement("div", {
              className: "flex space-x-4 w-full"
            }, React.createElement("div", {
                  className: "w-3/4"
                }, React.createElement("h1", {
                      className: "text-4xl"
                    }, "Chapter 1  The core language")), React.createElement("div", {
                  className: ""
                }, React.createElement("h2", {
                      className: ""
                    }, "Contents"), React.createElement("h3", {
                      className: ""
                    }, "1.1 Basics"), React.createElement("h3", {
                      className: ""
                    }, "1.2 Data types")));
}

var make = ManualCoreExamples;

var $$default = ManualCoreExamples;

export {
  s ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
