// Generated by ReScript, PLEASE EDIT WITH CARE


var data = {
  numberActiveMembers: 2000,
  industrySatisfactionPercent: 97,
  averagePrsPerWeek: 450
};

export {
  data ,
  
}
/* No side effect */
