// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Footer$Ocamlorg from "../components/Footer.js";

function MainLayout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "relative bg-white"
            }, null, React.createElement("div", {
                  className: "relative shadow"
                }, null), React.createElement("main", {
                  className: "bg-graylight"
                }, children), React.createElement("div", {
                  className: "relative"
                }, React.createElement(Footer$Ocamlorg.make, {})));
}

var make = MainLayout;

export {
  make ,
  
}
/* react Not a pure module */
