// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Book$Ocamlorg from "../../common/Book.js";
import * as TitleHeading$Ocamlorg from "../../components/TitleHeading.js";
import * as MainContainer$Ocamlorg from "../../components/MainContainer.js";
import * as SectionContainer$Ocamlorg from "../../components/SectionContainer.js";
import * as ConstructionBanner$Ocamlorg from "../../components/ConstructionBanner.js";

function s(prim) {
  return prim;
}

function ResourcesLanguage$UserLevelIntroduction(Props) {
  var content = Props.content;
  var margins = Props.margins;
  return React.createElement(SectionContainer$Ocamlorg.SmallCentered.make, {
              children: null,
              margins: margins,
              otherLayout: "flex items-center space-x-20"
            }, React.createElement("div", {
                  className: "text-5xl font-bold text-orangedark flex-shrink-0"
                }, content.level + " -"), React.createElement("div", {
                  className: "font-bold text-xl"
                }, content.introduction));
}

var UserLevelIntroduction = {
  make: ResourcesLanguage$UserLevelIntroduction
};

function ResourcesLanguage$Books(Props) {
  var margins = Props.margins;
  var content = Props.content;
  return React.createElement("div", {
              className: "bg-white overflow-hidden shadow rounded-lg mx-10 mx-auto max-w-5xl " + margins
            }, React.createElement("div", {
                  className: "px-4 py-5 sm:px-6 sm:py-9"
                }, React.createElement("h2", {
                      className: "text-center text-orangedark text-7xl font-bold mb-8 uppercase"
                    }, content.booksLabel), React.createElement("div", {
                      className: "grid grid-cols-5 items-center mb-8 px-6"
                    }, React.createElement("div", {
                          className: "flex justify-center"
                        }, React.createElement("svg", {
                              className: "h-24 center",
                              fill: "none",
                              viewBox: "0 0 90 159",
                              xmlns: "http://www.w3.org/2000/svg"
                            }, React.createElement("path", {
                                  clipRule: "evenodd",
                                  d: "M2.84806 86.0991L72.1515 155.595C76.1863 159.39 82.3571 159.39 86.1546 155.595C89.952 151.8 89.952 145.396 86.1546 141.601L23.734 79.2206L86.1546 16.8403C89.952 12.8081 89.952 6.64125 86.1546 2.84625C82.3571 -0.94875 76.1863 -0.94875 72.1515 2.84625L2.84806 72.105C-0.949387 76.1372 -0.949387 82.3041 2.84806 86.0991Z",
                                  fill: "#ED7109",
                                  fillRule: "evenodd"
                                }))), content.books.map(function (b, idx) {
                          return React.createElement("div", {
                                      key: idx.toString(),
                                      className: "flex justify-center"
                                    }, React.createElement("a", {
                                          href: b.link,
                                          target: "_blank"
                                        }, React.createElement("img", {
                                              className: "h-36 w-28",
                                              alt: b.name + " book",
                                              src: "/static/" + b.image
                                            })));
                        }), React.createElement("div", {
                          className: "flex justify-center"
                        }, React.createElement("svg", {
                              className: "h-24",
                              fill: "none",
                              viewBox: "0 0 90 159",
                              xmlns: "http://www.w3.org/2000/svg"
                            }, React.createElement("path", {
                                  clipRule: "evenodd",
                                  d: "M86.1546 72.3423L16.8512 2.84625C12.8164 -0.948746 6.64553 -0.948746 2.84809 2.84625C-0.949362 6.64127 -0.949362 13.0453 2.84809 16.8403L65.2686 79.2207L2.84809 141.601C-0.949362 145.633 -0.949362 151.8 2.84809 155.595C6.64553 159.39 12.8164 159.39 16.8512 155.595L86.1546 86.3363C89.952 82.3041 89.952 76.1373 86.1546 72.3423Z",
                                  fill: "#ED7109",
                                  fillRule: "evenodd"
                                }))))));
}

var Books = {
  make: ResourcesLanguage$Books
};

function ResourcesLanguage$Manual(Props) {
  var margins = Props.margins;
  return React.createElement(SectionContainer$Ocamlorg.MediumCentered.make, {
              children: null,
              margins: margins,
              paddingY: "pt-8 pb-14",
              filled: true
            }, React.createElement("h2", {
                  className: "text-center text-white text-7xl font-bold mb-8"
                }, "The OCaml Manual"), React.createElement("div", {
                  className: "mx-24 grid grid-cols-3 px-28 mx-auto max-w-4xl"
                }, React.createElement("div", {
                      className: "border-r-4 border-b-4"
                    }, React.createElement("div", {
                          className: "h-24 flex items-center justify-center px-4 font-bold bg-white mx-8 my-3 rounded"
                        }, React.createElement("p", {
                              className: "text-center"
                            }, React.createElement("a", {
                                  href: "https://ocaml.org/manual/index.html#sec6"
                                }, "Introduction Tutorials")))), React.createElement("div", {
                      className: "border-r-4 border-b-4"
                    }, React.createElement("div", {
                          className: "h-24 flex items-center justify-center px-4 font-bold bg-white mx-8 my-3 rounded"
                        }, React.createElement("p", {
                              className: "text-center"
                            }, React.createElement("a", {
                                  href: "https://ocaml.org/manual/stdlib.html"
                                }, "StdLib")))), React.createElement("div", {
                      className: "border-b-4"
                    }, React.createElement("div", {
                          className: "h-24 flex items-center justify-center px-4 font-bold bg-white mx-8 my-3 rounded"
                        }, React.createElement("p", {
                              className: "text-center"
                            }, React.createElement("a", {
                                  href: "https://ocaml.org/api/index.html"
                                }, "API Docs")))), React.createElement("div", {
                      className: "border-r-4"
                    }, React.createElement("div", {
                          className: "h-24 flex items-center justify-center px-4 font-bold bg-white mx-8 my-3 rounded"
                        }, React.createElement("p", {
                              className: "text-center"
                            }, React.createElement("a", {
                                  href: "https://ocaml.org/manual/index.html#sec72"
                                }, "Lang")))), React.createElement("div", {
                      className: "border-r-4"
                    }, React.createElement("div", {
                          className: "h-24 flex items-center justify-center px-4 font-bold bg-white mx-8 my-3 rounded"
                        }, React.createElement("p", {
                              className: "text-center"
                            }, React.createElement("a", {
                                  href: "https://ocaml.org/manual/extn.html#sec238"
                                }, "Ext")))), React.createElement("div", undefined, React.createElement("div", {
                          className: "h-24 flex items-center justify-center px-4 font-bold bg-white mx-8 my-3 rounded"
                        }, React.createElement("p", {
                              className: "text-center"
                            }, React.createElement("a", {
                                  href: "https://ocaml.org/manual"
                                }, "Something Else"))))));
}

var Manual = {
  make: ResourcesLanguage$Manual
};

function ResourcesLanguage$Applications(Props) {
  var margins = Props.margins;
  return React.createElement(SectionContainer$Ocamlorg.VerySmallCentered.make, {
              children: null,
              margins: margins
            }, React.createElement("h2", {
                  className: "text-center text-orangedark text-7xl font-bold mb-8"
                }, "Applications"), React.createElement("div", {
                  className: "sm:flex items-center space-x-32 mb-20"
                }, React.createElement("div", {
                      className: "mb-4 sm:mb-0 sm:mr-4"
                    }, React.createElement("p", {
                          className: "mt-1 mb-4 text-lg"
                        }, "Looking to learn more about the ways in which OCaml is used in real-world applications? Visit our Applications page to find out about different ways of using OCaml."), React.createElement("p", {
                          className: "text-right"
                        }, React.createElement("a", {
                              className: "text-orangedark underline",
                              href: "/resources/applications"
                            }, "Go to Applications >"))), React.createElement("div", {
                      className: "flex-shrink-0"
                    }, React.createElement("img", {
                          className: "h-48",
                          src: "/static/app-image2.png"
                        }))));
}

var Applications = {
  make: ResourcesLanguage$Applications
};

function ResourcesLanguage$Papers(Props) {
  var margins = Props.margins;
  return React.createElement("div", {
              className: "bg-white overflow-hidden shadow rounded-lg py-3 mx-auto max-w-5xl " + margins
            }, React.createElement("div", {
                  className: "px-4 py-5 sm:p-6"
                }, React.createElement("h2", {
                      className: "text-center text-orangedark text-7xl font-bold mb-8"
                    }, "PAPERS"), React.createElement("div", {
                      className: "grid grid-cols-3 mb-14 px-9 space-x-6 px-14"
                    }, React.createElement("div", {
                          className: ""
                        }, React.createElement("p", {
                              className: "text-orangedark text-7xl font-bold"
                            }, "1."), React.createElement("p", {
                              className: "font-bold"
                            }, React.createElement("a", {
                                  href: "https://arxiv.org/abs/1905.06543",
                                  target: "_blank"
                                }, "Extending OCaml's Open")), React.createElement("p", undefined, "by Runhang Li, Jeremey Yallop")), React.createElement("div", {
                          className: ""
                        }, React.createElement("p", {
                              className: "text-orangedark text-7xl font-bold"
                            }, "2."), React.createElement("p", {
                              className: "font-bold"
                            }, React.createElement("a", {
                                  href: "https://kcsrk.info/papers/memory_model_ocaml17.pdf",
                                  target: "_blank"
                                }, "A Memory Model for Multicore OCaml")), React.createElement("p", undefined, "by Stephen Dolan, KC Sivaramakrishnan")), React.createElement("div", {
                          className: ""
                        }, React.createElement("p", {
                              className: "text-orangedark text-7xl font-bold"
                            }, "3."), React.createElement("p", {
                              className: "font-bold"
                            }, React.createElement("a", {
                                  href: "https://arxiv.org/abs/1812.11664",
                                  target: "_blank"
                                }, "Eff Directly in OCaml")), React.createElement("p", undefined, "by Oleg Kiselyov, KC Sivaramakrishnan"))), React.createElement("div", {
                      className: "flex justify-center"
                    }, React.createElement("a", {
                          className: "font-bold inline-flex items-center px-10 py-3 border border-transparent text-base leading-4 font-medium rounded-md shadow-sm text-white bg-orangedark hover:bg-orangedarker",
                          href: "/resources/papers"
                        }, "Go to Papers"))));
}

var Papers = {
  make: ResourcesLanguage$Papers
};

function ResourcesLanguage(Props) {
  var content = Props.content;
  return React.createElement(React.Fragment, undefined, React.createElement(ConstructionBanner$Ocamlorg.make, {
                  figmaLink: "https://www.figma.com/file/36JnfpPe1Qoc8PaJq8mGMd/V1-Pages-Next-Step?node-id=1085%3A121",
                  playgroundLink: "/play/resources/language"
                }), React.createElement(MainContainer$Ocamlorg.None.make, {
                  children: null
                }, React.createElement(TitleHeading$Ocamlorg.Large.make, {
                      title: content.title,
                      pageDescription: content.pageDescription,
                      marginTop: "mt-1",
                      marginBottom: "mb-24",
                      addBottomBar: true
                    }), React.createElement(ResourcesLanguage$UserLevelIntroduction, {
                      content: content.beginning,
                      margins: "mb-20"
                    }), React.createElement(ResourcesLanguage$UserLevelIntroduction, {
                      content: content.growing,
                      margins: "mb-20"
                    }), React.createElement(ResourcesLanguage$Books, {
                      margins: "mb-16",
                      content: content.booksContent
                    }), React.createElement(ResourcesLanguage$UserLevelIntroduction, {
                      content: content.expanding,
                      margins: "mb-20"
                    }), React.createElement(ResourcesLanguage$Manual, {
                      margins: "mb-20"
                    }), React.createElement(ResourcesLanguage$UserLevelIntroduction, {
                      content: content.diversifying,
                      margins: "mb-20"
                    }), React.createElement(ResourcesLanguage$Applications, {
                      margins: "mb-36"
                    }), React.createElement(ResourcesLanguage$UserLevelIntroduction, {
                      content: content.researching,
                      margins: "mb-20"
                    }), React.createElement(ResourcesLanguage$Papers, {
                      margins: "mb-16"
                    })));
}

function getStaticProps(_ctx) {
  var books = Book$Ocamlorg.readAll(undefined);
  return {
          props: {
            content: {
              title: "Language",
              pageDescription: "This is the home of learning and tutorials. Whether you're a beginner, a teacher, or a seasoned researcher, this is where you can find the resources you need to accomplish your goals in OCaml.",
              beginning: {
                level: "Beginning",
                introduction: "Are you a beginner? Or just someone who wants to brush up on the fundamentals? In either case, the OFronds tutorial system has you covered!"
              },
              growing: {
                level: "Growing",
                introduction: "Familiar with the basics and looking to get a more robust understanding of OCaml? Or just curious? Check out the books available on OCaml:"
              },
              booksContent: {
                booksLabel: "Books",
                books: books
              },
              expanding: {
                level: "Expanding",
                introduction: "Have a strong foundation in OCaml? Time to get involved! Prepare by getting familiar with the OCaml Manual:"
              },
              diversifying: {
                level: "Diversifying",
                introduction: "Now that you're familiar with the building blocks of OCaml, you may want to diversify your portfolio and have a look at the many applications that operate using OCaml."
              },
              researching: {
                level: "Researching",
                introduction: "Aspiring towards greater understanding of the language? Want to push the limits and discover brand new things? Check out papers written by leading OCaml researchers:"
              }
            }
          }
        };
}

var make = ResourcesLanguage;

var $$default = ResourcesLanguage;

export {
  s ,
  UserLevelIntroduction ,
  Books ,
  Manual ,
  Applications ,
  Papers ,
  make ,
  getStaticProps ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
