// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function CommunityAroundWeb(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("a", {
                  className: "block underline",
                  href: "/play/community/aroundweb"
                }, "View Tailwind Playground"), React.createElement("div", {
                  className: "bg-graylight"
                }, React.createElement("div", {
                      className: "max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8"
                    }, React.createElement("div", {
                          className: "text-center"
                        }, React.createElement("p", {
                              className: "mt-1 text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-tight lg:text-6xl"
                            }, "OCaml Around the Web"), React.createElement("p", {
                              className: "max-w-4xl mt-5 mx-auto text-xl text-gray-500"
                            }, "Looking to interact with people who are also interested in OCaml? Find out about upcoming events, read up on blogs from the community, sign up for OCaml mailing lists, and discover even more places to engage with people from the community!")))), React.createElement("div", {
                  className: "bg-graylight pb-16"
                }, null, React.createElement("div", {
                      className: "bg-orangedark"
                    }, React.createElement("div", {
                          className: "max-w-2xl mx-auto text-center py-16 px-4 sm:py-20 sm:px-6 lg:px-8"
                        }, React.createElement("h2", {
                              className: "text-3xl font-extrabold text-white sm:text-4xl"
                            }, React.createElement("span", {
                                  className: "block"
                                }, "Want to engage with the OCaml Community?")), React.createElement("p", {
                              className: "mt-4 text-lg leading-6 text-white"
                            }, "Participate in discussions on everything OCaml over at discuss.ocaml.org, where members of the community post"), React.createElement("a", {
                              className: "mt-8 w-full inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md bg-white hover:bg-orangelight sm:w-auto",
                              href: "#"
                            }, "Take me to Discuss")))), React.createElement("div", {
                  className: "relative bg-graylight pt-16 pb-3 px-4 sm:px-6 lg:pt-24 lg:pb-8 lg:px-8"
                }, React.createElement("div", {
                      className: "absolute inset-0"
                    }, React.createElement("div", {
                          className: "bg-graylight h-1/3 sm:h-2/3"
                        })), React.createElement("div", {
                      className: "relative max-w-7xl mx-auto"
                    }, React.createElement("div", {
                          className: "text-center"
                        }, React.createElement("h2", {
                              className: "text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl"
                            }, "Recent Blog Posts"), React.createElement("p", {
                              className: "mt-3 max-w-2xl mx-auto text-xl text-gray-500 sm:mt-4"
                            }, "Be inspired by the work of OCaml programmers all over the world and stay up-to-date on the latest developments.")), React.createElement("div", {
                          className: "mt-12 max-w-lg mx-auto grid gap-5 lg:grid-cols-3 lg:max-w-none"
                        }, React.createElement("div", {
                              className: "flex flex-col rounded-lg shadow-lg overflow-hidden"
                            }, React.createElement("div", {
                                  className: "flex-shrink-0"
                                }, React.createElement("img", {
                                      className: "h-48 w-full object-cover",
                                      alt: "",
                                      src: "https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80"
                                    })), React.createElement("div", {
                                  className: "flex-1 bg-white p-6 flex flex-col justify-between"
                                }, React.createElement("div", {
                                      className: "flex-1"
                                    }, React.createElement("p", {
                                          className: "text-sm font-medium text-orangedark"
                                        }, React.createElement("a", {
                                              className: "hover:underline",
                                              href: "#"
                                            }, "Blog")), React.createElement("a", {
                                          className: "block mt-2",
                                          href: "#"
                                        }, React.createElement("p", {
                                              className: "text-xl font-semibold text-gray-900"
                                            }, "What I learned Coding from Home"), React.createElement("p", {
                                              className: "mt-3 text-base text-gray-500"
                                            }, "Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto accusantium praesentium eius, ut atque fuga culpa, similique sequi cum eos quis dolorum."))), React.createElement("div", {
                                      className: "mt-6 flex items-center"
                                    }, React.createElement("div", {
                                          className: "flex-shrink-0"
                                        }, React.createElement("a", {
                                              href: "#"
                                            }, React.createElement("span", {
                                                  className: "sr-only"
                                                }, "Roel Aufderehar"), React.createElement("img", {
                                                  className: "h-10 w-10 rounded-full",
                                                  alt: "",
                                                  src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                                                }))), React.createElement("div", {
                                          className: "ml-3"
                                        }, React.createElement("p", {
                                              className: "text-sm font-medium text-gray-900"
                                            }, React.createElement("a", {
                                                  className: "hover:underline",
                                                  href: "#"
                                                }, "Roel Aufderehar")), React.createElement("div", {
                                              className: "flex space-x-1 text-sm text-gray-500"
                                            }, React.createElement("time", {
                                                  dateTime: "2020-03-16"
                                                }, "Mar 16, 2020"), React.createElement("span", {
                                                  "aria-hidden": true
                                                }, "&middot;"), React.createElement("span", undefined, "6 min read")))))), React.createElement("div", {
                              className: "flex flex-col rounded-lg shadow-lg overflow-hidden"
                            }, React.createElement("div", {
                                  className: "flex-shrink-0"
                                }, React.createElement("img", {
                                      className: "h-48 w-full object-cover",
                                      alt: "",
                                      src: "https://images.unsplash.com/photo-1547586696-ea22b4d4235d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80"
                                    })), React.createElement("div", {
                                  className: "flex-1 bg-white p-6 flex flex-col justify-between"
                                }, React.createElement("div", {
                                      className: "flex-1"
                                    }, React.createElement("p", {
                                          className: "text-sm font-medium text-orangedark"
                                        }, React.createElement("a", {
                                              className: "hover:underline",
                                              href: "#"
                                            }, "Blog")), React.createElement("a", {
                                          className: "block mt-2",
                                          href: "#"
                                        }, React.createElement("p", {
                                              className: "text-xl font-semibold text-gray-900"
                                            }, "Programming for a Better World"), React.createElement("p", {
                                              className: "mt-3 text-base text-gray-500"
                                            }, "Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit facilis asperiores porro quaerat doloribus, eveniet dolore. Adipisci tempora aut inventore optio animi., tempore temporibus quo laudantium."))), React.createElement("div", {
                                      className: "mt-6 flex items-center"
                                    }, React.createElement("div", {
                                          className: "flex-shrink-0"
                                        }, React.createElement("a", {
                                              href: "#"
                                            }, React.createElement("span", {
                                                  className: "sr-only"
                                                }, "Brenna Goyette"), React.createElement("img", {
                                                  className: "h-10 w-10 rounded-full",
                                                  alt: "",
                                                  src: "https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                                                }))), React.createElement("div", {
                                          className: "ml-3"
                                        }, React.createElement("p", {
                                              className: "text-sm font-medium text-gray-900"
                                            }, React.createElement("a", {
                                                  className: "hover:underline",
                                                  href: "#"
                                                }, "Brenna Goyette")), React.createElement("div", {
                                              className: "flex space-x-1 text-sm text-gray-500"
                                            }, React.createElement("time", {
                                                  dateTime: "2020-03-10"
                                                }, "Mar 10, 2020"), React.createElement("span", {
                                                  "aria-hidden": true
                                                }, "&middot;"), React.createElement("span", undefined, "4 min read")))))), React.createElement("div", {
                              className: "flex flex-col rounded-lg shadow-lg overflow-hidden"
                            }, React.createElement("div", {
                                  className: "flex-shrink-0"
                                }, React.createElement("img", {
                                      className: "h-48 w-full object-cover",
                                      alt: "",
                                      src: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80"
                                    })), React.createElement("div", {
                                  className: "flex-1 bg-white p-6 flex flex-col justify-between"
                                }, React.createElement("div", {
                                      className: "flex-1"
                                    }, React.createElement("p", {
                                          className: "text-sm font-medium text-orangedark"
                                        }, React.createElement("a", {
                                              className: "hover:underline",
                                              href: "#"
                                            }, "Talk")), React.createElement("a", {
                                          className: "block mt-2",
                                          href: "#"
                                        }, React.createElement("p", {
                                              className: "text-xl font-semibold text-gray-900"
                                            }, "Methods for Irmin V2"), React.createElement("p", {
                                              className: "mt-3 text-base text-gray-500"
                                            }, "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint harum rerum voluptatem quo recusandae magni placeat saepe molestiae, sed excepturi cumque corporis perferendis hic."))), React.createElement("div", {
                                      className: "mt-6 flex items-center"
                                    }, React.createElement("div", {
                                          className: "flex-shrink-0"
                                        }, React.createElement("a", {
                                              href: "#"
                                            }, React.createElement("span", {
                                                  className: "sr-only"
                                                }, "Daniela Metz"), React.createElement("img", {
                                                  className: "h-10 w-10 rounded-full",
                                                  alt: "",
                                                  src: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                                                }))), React.createElement("div", {
                                          className: "ml-3"
                                        }, React.createElement("p", {
                                              className: "text-sm font-medium text-gray-900"
                                            }, React.createElement("a", {
                                                  className: "hover:underline",
                                                  href: "#"
                                                }, "Daniela Metz")), React.createElement("div", {
                                              className: "flex space-x-1 text-sm text-gray-500"
                                            }, React.createElement("time", {
                                                  dateTime: "2020-02-12"
                                                }, "Feb 12, 2020"), React.createElement("span", {
                                                  "aria-hidden": true
                                                }, "&middot;"), React.createElement("span", undefined, "11 min read")))))))), React.createElement("p", {
                      className: "mt-5 text-right"
                    }, React.createElement("a", {
                          className: "font-semibold text-orangedark",
                          href: ""
                        }, "Go to the blog archive >"))), React.createElement("div", {
                  className: "bg-graylight"
                }, React.createElement("div", {
                      className: "max-w-7xl mx-auto py-6 px-4 sm:py-12 sm:px-6 lg:px-8"
                    }, React.createElement("div", {
                          className: "text-center"
                        }, React.createElement("p", {
                              className: "text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl"
                            }, "Looking for More? Try these spaces:")))), React.createElement("div", {
                  className: "bg-graylight"
                }, React.createElement("div", {
                      className: "mx-auto max-w-4xl flex pb-14 space-x-24 justify-center"
                    }, React.createElement("div", {
                          className: "grid grid-cols-1 lg:grid-cols-2 gap-3"
                        }, React.createElement("div", {
                              className: "text-center bg-white shadow overflow-hidden rounded-md px-36 py-4"
                            }, "Github.com"), React.createElement("div", {
                              className: "text-center bg-white shadow overflow-hidden rounded-md px-36 py-4"
                            }, "Reddit.com"), React.createElement("div", {
                              className: "text-center bg-white shadow overflow-hidden rounded-md px-36 py-4"
                            }, "Twitter.com"), React.createElement("div", {
                              className: "text-center bg-white shadow overflow-hidden rounded-md px-36 py-4"
                            }, "Discuss.ocaml.org"), React.createElement("div", {
                              className: "text-center bg-white shadow overflow-hidden rounded-md px-36 py-4"
                            }, "Github.com"), React.createElement("div", {
                              className: "text-center bg-white shadow overflow-hidden rounded-md px-36 py-4"
                            }, "Github.com")))));
}

var make = CommunityAroundWeb;

var $$default = CommunityAroundWeb;

export {
  s ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
