// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TitleHeading$Ocamlorg from "../../components/TitleHeading.js";
import * as MainContainer$Ocamlorg from "../../components/MainContainer.js";
import * as ConstructionBanner$Ocamlorg from "../../components/ConstructionBanner.js";

function s(prim) {
  return prim;
}

var contentEn = {
  title: "Events",
  pageDescription: "Several events take place in the OCaml community over the course of each year, in countries all over the world. This calendar will help you stay up to date on what is coming up in the OCaml sphere."
};

function CommunityEvents(Props) {
  var contentOpt = Props.content;
  var content = contentOpt !== undefined ? contentOpt : contentEn;
  return React.createElement(React.Fragment, undefined, React.createElement(ConstructionBanner$Ocamlorg.make, {
                  figmaLink: "https://www.figma.com/file/36JnfpPe1Qoc8PaJq8mGMd/V1-Pages-Next-Step?node-id=1176%3A0"
                }), React.createElement(MainContainer$Ocamlorg.Centered.make, {
                  children: React.createElement(TitleHeading$Ocamlorg.Large.make, {
                        title: content.title,
                        pageDescription: content.pageDescription
                      })
                }));
}

var make = CommunityEvents;

var $$default = CommunityEvents;

export {
  s ,
  contentEn ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
