// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TitleHeading$Ocamlorg from "../../components/TitleHeading.js";
import * as MainContainer$Ocamlorg from "../../components/MainContainer.js";
import * as SectionContainer$Ocamlorg from "../../components/SectionContainer.js";
import * as ConstructionBanner$Ocamlorg from "../../components/ConstructionBanner.js";

function s(prim) {
  return prim;
}

var companies = [
  {
    logo: "oclabs.png",
    name: "OCaml Labs",
    customWidth: undefined,
    needsRounding: false,
    website: "https://ocamllabs.io"
  },
  {
    logo: "trd.png",
    name: "Tarides",
    customWidth: "w-40",
    needsRounding: false,
    website: "https://tarides.com"
  },
  {
    logo: "slv2.png",
    name: "Solvuu",
    customWidth: undefined,
    needsRounding: true,
    website: "https://solvuu.com"
  },
  {
    logo: "js2.jpeg",
    name: "Jane Street",
    customWidth: undefined,
    needsRounding: true,
    website: "https://janestreet.com"
  },
  {
    logo: "lxf.png",
    name: "LexiFi",
    customWidth: undefined,
    needsRounding: false,
    website: "https://lexifi.com"
  },
  {
    logo: "tz.png",
    name: "Tezos",
    customWidth: "w-24",
    needsRounding: false,
    website: "https://tezos.com"
  }
];

var contentEn_title = "Industrial Users of OCaml";

var contentEn_pageDescription = "OCaml is a popular choice for companies who make use of its features in key aspects of their technologies. Some companies that use OCaml code are listed below:";

var contentEn = {
  title: contentEn_title,
  pageDescription: contentEn_pageDescription,
  companies: companies
};

function IndustryUsers$LogoSection(Props) {
  var margins = Props.margins;
  var companies = Props.companies;
  return React.createElement(SectionContainer$Ocamlorg.ResponsiveCentered.make, {
              children: React.createElement("div", {
                    className: "flex flex-wrap justify-center lg:justify-between "
                  }, companies.map(function (c, idx) {
                        var width = c.customWidth;
                        return React.createElement("div", {
                                    key: idx.toString(),
                                    className: "p-12 flex flex-col items-center"
                                  }, React.createElement("img", {
                                        className: (
                                          width !== undefined ? width : " w-32 "
                                        ) + (
                                          c.needsRounding ? " rounded-full " : ""
                                        ) + " mb-9 ",
                                        alt: "",
                                        src: "/static/" + c.logo
                                      }), React.createElement("p", {
                                        className: "text-4xl underline font-bold"
                                      }, React.createElement("a", {
                                            href: c.website,
                                            target: "_blank"
                                          }, c.name)));
                      })),
              margins: margins
            });
}

var LogoSection = {
  make: IndustryUsers$LogoSection
};

function IndustryUsers(Props) {
  var contentOpt = Props.content;
  var content = contentOpt !== undefined ? contentOpt : contentEn;
  return React.createElement(React.Fragment, undefined, React.createElement(ConstructionBanner$Ocamlorg.make, {
                  figmaLink: "https://www.figma.com/file/36JnfpPe1Qoc8PaJq8mGMd/V1-Pages-Next-Step?node-id=430%3A36400",
                  playgroundLink: "/play/industry/users"
                }), React.createElement(MainContainer$Ocamlorg.Centered.make, {
                  children: null
                }, React.createElement(TitleHeading$Ocamlorg.Large.make, {
                      title: content.title,
                      pageDescription: content.pageDescription,
                      marginTop: "mt-2",
                      callToAction: {
                        label: "Success Stories",
                        url: "/industry/successstories"
                      }
                    }), React.createElement(IndustryUsers$LogoSection, {
                      margins: "mt-6",
                      companies: content.companies
                    })));
}

var Link;

var make = IndustryUsers;

var $$default = IndustryUsers;

export {
  Link ,
  s ,
  companies ,
  contentEn ,
  LogoSection ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
